--- # this is my first Playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  vars:
   ansible_version1: 2.7
   software_install: git
  tasks:
   - name: Install Git on Client hosts using {{ ansible_version1 }}
     yum: pkg={{ software_install }} state=installed
   - name: Install httpd on Client hosts
     yum: pkg=httpd state=installed
