--- # this is my first Playbook
- hosts: all
  user: ansadmin
  become: true
  connection: ssh
  gather_facts: no
  vars:
   ansible_version1: 2.7
   software_install: git
  vars_files:
   config/software_web.yml
  tasks:
   - name: Install Git on Client hosts using {{ ansible_version1 }}
     yum: pkg={{ git_client }} state=installed
   - name: Install httpd on Client hosts
     yum: pkg={{ httpd_server }} state=installed
